# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MAT 4953/6973 Math Found AI
tagline: A special topics course at the University of Texas at San Antonio
description: A special introductory course to the theory of AI (UTSA, Spring 2026)
author: Eduardo Due√±ez
baseurl: '/MathAIspring2026UTSA' # the subpath of your site, e.g. /blog
url: 'https://eduenez.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

enable_math: true
math:
  provider: mathjax

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
favicon_ico : "/assets/images/favicon.ico"
logo: "/assets/images/math_of_ai.png"
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Canvas:
    - 'https://utsa.instructure.com/courses/81120'
footer_content:

# Collections for website data
collections_dir: collections
collections:
  staffers:
  modules:
  schedules:
  announcements:
  refdocs:
    permalink: ":collection/:path"
    output: true

  assignments:
    # output: true
    # permalink: ":collection/:path"

just_the_docs:
  collections:
    refdocs:
      name: Reference documents
    assignments:
      name: Assignments

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      subpath: '/assets/images/'
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  # - scope:
  #     path: ''
  #     type: assignments
  #   values:
  #     layout: assignment

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true
